version: '3'

services:
  container-a:
    build:
      context: ./container-a
    ports:
      - "8080:8080"

  container-b:
    build:
      context: ./container-b
    depends_on:
      - container-a